--- 

- name: Configure EIGRP on all routers

  hosts: routers

  gather_facts: false 

  connection: network_cli

  

  tasks: 

   - name: Configure EIGRP

     ios_config:

      save_when: modified

      lines:

        - network 0.0.0.0 0.0.0.0

        - redistribute static

      parents: router eigrp 70

     register: output

  

   - name: Print to console

     debug: var=output